development:
  sessions:
    default:
      uri: <%= URI.parse(ENV['MONGOLAB_URI']) %>
      options:
        max_retries: 30
        retry_interval: 1
        timeout: 15
        refresh_interval: 10

production:
  sessions:
    default:
      uri: <%= URI.parse(ENV['MONGOLAB_URI']) %>
      options:
        max_retries: 30
        retry_interval: 1
        timeout: 15
        refresh_interval: 10
