development:
  sessions:
    default:
      uri: <% mongo_uri %>
      options:
        max_retries: 30
        retry_interval: 1
        timeout: 15
        refresh_interval: 10

production:
  sessions:
    default:
      uri: <% mongo_uri %>
      options:
        max_retries: 30
        retry_interval: 1
        timeout: 15
        refresh_interval: 10
