development:
  sessions:
    default:
      database: readwriteretribution
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: readwriteretribution
      hosts:
        - localhost:27017

