development:
  sessions:
    default:
      database: mongoid
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: mongoid
      hosts:
        - localhost:27017

